openapi: 3.0.0

info:
  title: Columbia API
  description: API description in Markdown.
  version: 1.0.0

servers:
  - url: /api/v1
    description: Relative path

paths:
  /hello_world:
    get:
      operationId: columbia.api_v1.hello_world.get
      responses:
        200:
          description: OK
  /hello_task:
    get:
      operationId: columbia.api_v1.hello_world.remote
      responses:
        200:
          description: OK
